### PR TITLE
Add date to migrations

### PR DESCRIPTION
**Pull request by aalaap**
Instead of copying over migration files with hardcoded dates going back to 2016, the current date can be added to the filenames during publishing.

### CODE REVIEW

**Comment by Omranic** [comment]
And what's the problem with "**copying over migration files with hardcoded dates going back to 2016**"? 🤔

**Comment by aalaap** [comment]
Sequence of creating tables gets affected. In a project started in 2016, for example, after 100 tables, if one adds this package, the next time the project is deployed, that migration will run before any other table. If there are dependencies, it's even more of a problem.

**Comment by MannikJ** [comment]
@aalaap @Omranic 
I think creating a new timestamp when publishing shouldn't be something to argue about, but does it even work without the option to deactivate the auto-loading of the migrations as suggested in #27?

I can only concur once again that how the migrations are handled within this packageshould be improved. Various conflicts are inevitable, because of its inflexibility. 
In fact I had to create a fork just to use that package within our application because of conflicting migrations and no options to change the behavior.

**Comment by Omranic** [comment]
Thank you for your valuable input, this is currently "work-in-progress", once ready and we're confident of the positive change it will bring to package users, we'll commit & release a new major version. And by WIP I mean we're working on this now 🙂

**Comment by MannikJ** [comment]
It might be convincing to mention that adding the current timestamp to the migration file when publishing  is how Spatie does it in almost all of their packages. Shouldn't be too wrong then I think :)

But I should also add that most of their packages were created before it was genereally recommended to use `loadMigrationsFrom` instead of the publish mechanism. Although they still seem to prefer publishing because of its flexibility.
I think offering both styles plus the option to deactivate auto-loading would be even better.

Maybe a [ `class_exists` check](https://github.com/spatie/laravel-tags/blob/master/src/TagsServiceProvider.php#L15) could also be valuable to avoid conflicts without having the user to deactivate it explicitly.

**Comment by Omranic** [comment]
All packages have been updated to include this feature, check latest releases 😉 enjoy!

**Pull request closed without merging**
