### PR TITLE
Update spatie/laravel-translatable

### LINKED ISSUE #47: Update Required Dependency spatie/laravel-translatable
The title says it. We have a dependency conflict because this package requires v^3.1.0 of spatie/laravel-translatable and we have another package installed that requires v^4.0 so composer can't find a version that satisfies both packages.
My suggestion would be to update this package's dependency to ^4.0.

Related to #39 

The error message:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.8.17
    - Conclusion: don't install laravel/framework v5.8.17
    - spatie/laravel-translatable 3.1.0 requires laravel/framework ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - spatie/laravel-translatable 3.1.1 requires laravel/framework ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - spatie/laravel-translatable 3.1.2 requires laravel/framework ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.8.17].
    - Can only install one of: laravel/framework[5.6.x-dev, v5.8.17].
    - Can only install one of: laravel/framework[5.7.x-dev, v5.8.17].
    - Installation request for laravel/framework (locked at v5.8.17, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.17].
    - Installation request for rinvex/laravel-categories ^2.0 -> satisfiable by rinvex/laravel-categories[v2.0.0].
    - Conclusion: don't install spatie/laravel-translatable 4.1.1|install spatie/laravel-translatable 3.1.0|install spatie/laravel-translatable 3.1.1|install spatie/laravel-translatable 3.1.2
    - Conclusion: remove spatie/laravel-translatable 4.1.1|install spatie/laravel-translatable 3.1.0|install spatie/laravel-translatable 3.1.1|install spatie/laravel-translatable 3.1.2
    - rinvex/laravel-categories v2.0.0 requires spatie/laravel-translatable ^3.1.0 -> satisfiable by spatie/laravel-translatable[3.1.0, 3.1.1, 3.1.2, 3.1.3, v3.x-dev].
    - Can only install one of: spatie/laravel-translatable[3.1.3, 4.1.1].
    - Can only install one of: spatie/laravel-translatable[v3.x-dev, 4.1.1].
    - Installation request for spatie/laravel-translatable (locked at 4.1.1) -> satisfiable by spatie/laravel-translatable[4.1.1].


Installation failed, reverting ./composer.json to its original content.
```

### PR DESCRIPTION
**Pull request by MannikJ**
Fixes #47

### CODE REVIEW

**Comment by MannikJ** [comment]
Only working for PHP ^7.2

**Comment by user00265** [comment]
Looks like the TravisCI errors are related to a PHP 7.1 job being ran, but the tests require 7.2 at the least.

**Comment by Omranic** [comment]
Thank you for the PR / All PR should be submitted to the develop branch ([contributing tips](https://github.com/rinvex/laravel-categories/blob/master/CONTRIBUTING.md#pull-requests))

**Comment by Omranic** [comment]
Fixed in 8d8de0b9612651231a19e993c417dbfb9fd3041d

**Pull request closed without merging**
